export const ALLOWED_UPGRADE_DELAY = 2886195 // exceptional case: first upgrade
export const OPERATORS_SEARCH_QUERY_STEP = 600 // 10min in sec
export const IS_BEACON_AUTHORIZED = "isBeaconAuthorized"
export const BEACON_AUTHORIZATION = "beaconAuthorization"
export const IS_TBTC_AUTHORIZED = "isTbtcAuthorized"
export const TBTC_AUTHORIZATION = "tbtcAuthorization"
export const IS_UP_TIME_SATISFIED = "isUptimeSatisfied"
export const IS_PRE_PARAMS_SATISFIED = "isPreParamsSatisfied"
export const PRECISION = 1000000
export const QUERY_RESOLUTION = 60 // 1min sampling time for the metrics
export const HUNDRED = 100
export const IS_VERSION_SATISFIED = "isVersionSatisfied"
export const APR = 15 // percent
export const SECONDS_IN_YEAR = 31536000
